name: GitHub Actions Runner in Docker - Latest
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - Dockerfile.base
      - README.md
    branches:
      - master
      - develop

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  ubuntu_latest_deploy:
    runs-on: ubuntu-latest
    env: 
      DOCKER_REGISTRY: eu.gcr.io
    outputs:
      sha-short: ${{ steps.vars-step.outputs.sha-short }}
    steps:
      - name: Init git vars
        shell: bash
        id: vars-step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          K8S_SA: ${{ secrets.K8S_SET_IMAGE_SA_KEY }}
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            export JSON_RESP=`curl -s --request GET --url "${{ github.event.issue.pull_request.url }}" --header "Authorization: Bearer $GH_TOKEN"`
            echo "sha-short=`echo $JSON_RESP | jq -r .head.sha | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=`echo $JSON_RESP | jq -r .head.ref`" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF = *refs/heads/* ]]; then
            echo "sha-short=`echo $GITHUB_SHA | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            echo "sha-short=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
          fi
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Update Dockerfile FROM org
        run: sed -i.bak "s/FROM.*/FROM ${DOCKER_REGISTRY}\/${{ secrets.GKE_PROJECT_ID }}\/github-runner-base:master/" Dockerfile
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_IMAGE_PUSH_SA_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          pull: true
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.GKE_PROJECT_ID }}/github-runner:${{ steps.vars-step.outputs.sha-short }}
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.GKE_PROJECT_ID }}/github-runner:${{ steps.vars-step.outputs.branch }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ env.K8S_SA }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: "Connect to cluster"
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: staging
          location: europe-west1-b
          project_id: ${{ secrets.GKE_PROJECT_ID }}
      - name: Deploy
        run: |-
          kubectl set image deployment solsten-runner-staging -n daemon solsten-runner-staging=${{ env.DOCKER_REGISTRY }}/${{ secrets.GKE_PROJECT_ID }}/solsten-runner:${{ steps.vars-step.outputs.sha-short }}
          kubectl rollout status deployment/solsten-runner-staging -n daemon
