#on:
#  pull_request:
#
#name: "Trigger: Push action"
#
#jobs:
#  tests:
#    name: Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#      - uses: actions/setup-python@v5
#      - uses: pre-commit/action@v3.0.1
#      - name: Run ShellCheck
#        uses: ludeeus/action-shellcheck@master
